---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: lazyblue
description: Vanilla Fedora Silverblue with some quality of life improvements

base-image: quay.io/fedora/fedora-silverblue
image-version: 42

alt-tags:
  - stable

modules:
  - from-file: tweaks.yml
