---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: lazyblue
description: Vanilla Fedora Silverblue with some quality of life improvements

base-image: quay.io/fedora/fedora-silverblue
image-version: 42

modules:
  - from-file: tweaks/proprietary.yml
  - from-file: tweaks/packages.yml
  - from-file: tweaks/flatpaks.yml
  - from-file: tweaks/desktop-theme.yml
  - from-file: tweaks/disable-automount.yml

  - type: signing
